In [12]:
lst=['apple','banana','cherry','guava','man']
n=3
def filter_long_words(lst,n):
    lst1=[]
    for i in lst:
        k=len(i)
        if k>n:
            lst1.append(i)
            print(i)
    return lst
lst1=[]
lst1=filter_long_words(lst,n)  
print(lst1)

apple
banana
cherry
guava
['apple', 'banana', 'cherry', 'guava', 'man']


In [16]:
# write a python function which takes parameter as char and return true if it is vovel
def isvovel(i):
        if(i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
            return True
        else:
            return False

lst=['a','e','i','c','d']
for i in lst:
    a=isvovel(i)
    print(a) 
print("--------------------------------------------------------------------------------------------------------------------------")
str='Sanjivani'
for i in str:
    b=isvovel(i)
    print(b)             
    

True
True
True
False
False
--------------------------------------------------------------------------------------------------------------------------
False
True
False
False
True
False
True
False
True


In [19]:
import numpy as np
np.version.version

'1.21.4'

In [20]:
lst=[1,2,3,4]
a=np.array(lst)
type(a)

numpy.ndarray

In [32]:
a.shape

(4,)

In [37]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [25]:
lst=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
type(lst)


list

In [26]:
b=np.array(lst)
b.shape

(4, 3)

In [27]:
type(b)

numpy.ndarray

In [31]:
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
#b.reshape(2,8)
#valueError

In [38]:
arr=[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]

In [39]:
arr=np.array(arr)

In [40]:
arr.shape


(1, 3, 4)

In [44]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [46]:
np.array([1,2,3,4],dtype = int)


array([1, 2, 3, 4])

In [47]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [53]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
b[1:3][0:2]

array([[4, 5, 6],
       [7, 8, 9]])

In [56]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
b[1:3,1:3]

array([[5, 6],
       [8, 9]])

# matrix

In [58]:
type(np.mat([1,2,3,4]))

numpy.matrix

In [59]:
np.mat('1,2,3,4')

matrix([[1, 2, 3, 4]])

In [60]:
arr1=np.array([12,34,5])
print(arr1)
type(arr1)

[12 34  5]


numpy.ndarray

In [61]:
arr2=np.asarray([12,34,5])
print(arr2)
type(arr2)

[12 34  5]


numpy.ndarray

In [96]:
arr3=np.asanyarray([12,34,5])
print(arr3)
type(arr3)


[12 34  5]


numpy.ndarray

# from function

In [62]:
a=np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

In [63]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [103]:
type(a)

numpy.ndarray

In [64]:
print(*np.zeros(5))

0.0 0.0 0.0 0.0 0.0


# np.zeros or ones

In [106]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [108]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [65]:
np.ones((3,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [66]:
np.empty((3,6))

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306,
        1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306,
        1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307,
        9.34609790e-307, 3.91792279e-317, 8.34444288e-308]])

In [67]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
print(np.linspace(4,12,3)) #devide into 3rd argument parts starts from 1st arg and ends with second

[ 4.  8. 12.]


In [74]:
b=np.ones((4,5,2))

In [75]:
b.ndim

3

In [76]:
b.shape

(4, 5, 2)

In [77]:
b.dtype

dtype('float64')

In [78]:
np.arange(16).ndim

1

In [130]:
np.arange(16).shape

(16,)

In [80]:
a=np.arange(16).reshape(2,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [145]:
a.ndim

2

In [81]:
np.arange(16).reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [82]:
np.diag(a)

array([0, 9])

In [83]:
np.diag(a,k=2)

array([ 2, 11])

In [152]:
np.diag(a,k=-1)

array([8])

In [84]:
for i in range(1,6):
    for j in range(1,i+1):
        print("*",end='')
    print()    

*
**
***
****
*****


In [163]:
def myreduce1(max1,lst):
    return a
def max1(a,b):
    if(a>b):
        return a
    else:
        return b
lst=[92,34,198]
a=0
for i in range(0,len(lst)):
    b=lst[i]
    a=max1(a,b)
print(myreduce1(max1,lst))    

198


In [168]:
word=input("Eneter the word:")
word[::-1]
#word=word.reverse()


Eneter the word:aniket


'tekina'

Write a program to find volume of sphere 4/3 pi r^3 with diameter 12 cm

In [177]:
import math
diameter = int ( input ( "Enter Diameter:" ) )
radius = diameter/2
volume = 4/3 * math.pi * (radius**3)
print(volume)

Enter Diameter:12
904.7786842338603



Write a program to accept users first and last name and then priting in reverse order

In [178]:
fname=input()
lname=input()
print("{} {}".format(lname,fname))

aniket
jawale
jawale aniket


prgram to find all such numbers which are divisible by 7 but are not multiple of 5,between 2000 and 3200(both inclued) the numbers should be printed in comma seperated sequence

In [179]:
for i in range(2000,3201):
    if(i%7==0 and i%5!=0):
        print(i,end=",")

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199,

In [180]:
#write a numpy program ro compute cross product of 2 giverr vectors

In [85]:
import numpy as np
a=[[1,2],[3,4]]
a=np.array(a)
b=[[4,3],[7,8]]
b=np.array(b)
def cross_product(a,b):
    print("first vector:",a)
    print("Second vector:",b)
    return np.cross(a,b)
cross=cross_product(a,b)
print("cross product:",cross)
    

first vector: [[1 2]
 [3 4]]
Second vector: [[4 3]
 [7 8]]
cross product: [-5 -4]


In [86]:
a=[1,2]
b=[4,3]
cross=(a[0]*b[1])-(a[1]*b[0])
print(cross)

-5
